### ISSUE TITLE
Team name on final

### ISSUE THREAD

**Issue by roniwahyu** [lipp15/bracket-world#1]
How to setup team name and score from first round to final bracket? i mean how to fill up all of brackets posititions, thanks..

**Comment by lipp15** [comment]
Thanks for your interest in the plugin. At the moment, I only have it configured to accept the initial set up of the bracket so unfortunately there's no easy way to populate all of the positions. If you go to bracket-world.com and set up a username/password, you can see what a completed bracket looks like. It has a slightly different look than what is produced by the plug-in, but it will give you a sense of what needs to be built out. You can do the following after login:
1. Click on 'Search Brackets' from the top navigation
2. Open the 'Search Options' Panel
3. Choose a status of 'Completed'
4. Click the 'Search With Options' button
5. Click the ;View Bracket; button on the ;2014 FIFA World Cup' line

Here's a screenshot of the search steps:

![bracket-world-search](https://cloud.githubusercontent.com/assets/5321741/5675367/18935efa-9782-11e4-8118-2112176f430a.png)

Within bracket-world.com you can also create a bracket and set the winners, so depending on what you're looking to do, you may be able to accomplish this through the user interface on this site as opposed to through code with the plugin.

Hope this is helpful. Best of luck.

**Comment by roniwahyu** [comment]
thanks for your support, it's helpful on bracket-world.com, but i mean..how to setup your jquery bracket js library to make it complete bracket? i building custom apps to display complete tournament bracket with your jquery plugin.

thanks you

**Comment by lipp15** [comment]
Hello, apologies for the extremely long delay in responding. My wife and I had twins a few weeks ago and I haven't had much time to devote to anything but child care and work. To do what you're looking for within the plugin would take a good deal of effort and I don't have any plans to extend it at the moment. That said, it shouldn't be too difficult to write the code yourself to accommodate what you're looking to do. After invoking the plugin with whatever initial state you'd like, most of the DOM that you'll need will have already been created on the page. You would simply need to target those areas of the DOM where the team names are placed and insert the names of the winners of subsequent rounds along with any other additional info that you'd like and adjust some CSS. Unfortunately, I won't be able to help much more than that.

Best of luck,
Mike

**Comment by roniwahyu** [comment]
Hi Mike, 
Its a great news here, Congratulations for your twins, it's awesome. are they boys or girls?.
Thanks for your attention, i appreciate that. I will review your bracket.
again, thank you, it's a great sharing...

regards,
Roniwahyu
Indonesia

**Comment by lipp15** [comment]
Thanks Roniwahyu - we had two boys bringing my total to 3 boys. It's a lot
to deal with but very worth it! Best of luck to you.
- Mike

On Sun, Feb 22, 2015 at 5:48 PM, Syahroni Wahyu notifications@github.com
wrote:

> Hi Mike,
> Its a great news here, Congratulations for your twins, it's awesome. are
> they boys or girls?.
> Thanks for your attention, i appreciate that. I will review your bracket.
> again, thank you, it's a great sharing...
> 
> regards,
> Roniwahyu
> Indonesia
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lipp15/bracket-world/issues/1#issuecomment-75472757.

## 
- Mike
